### ISSUE TITLE
Fragments fail to deserialize with RESTSerializer

### ISSUE THREAD

**Issue by Truffula** [lytics/ember-data-model-fragments#130]
Using RESTSerializer with Ember Data 1.13.11, fragments are not deserialized unless the serializer has the undocumented property `isNewSerializerAPI: true`.

I have some customisations on the serializer, but as far as I can tell the Model Fragment deserializer is receiving a valid JSONAPI object.

**Comment by slindberg** [comment]
I don't have an app that is running ED 1.13.11 yet, but [I attempted to reproduce in a test and didn't run into trouble](https://github.com/lytics/ember-data.model-fragments/commit/4634e10d6493e584b495760a5ea012965b4a9ab1). Can you elaborate more about the failure? Note that fragment attributes shouldn't be nested JSONAPI objects themselves, they should just be plain objects/arrays since the type can be inferred from the property definitions.

```json
{
  "id": "1",
  "attributes": {
    "foo": { <--DS.hasOneFragment
      "baz": true
    },
    "bar": [ <--DS.hasManyFragments
      {
        "quux": false
      }
    ]
  }
}
```

**Comment by Truffula** [comment]
Thanks @slindberg, I'll see if I can reproduce an example for you.

**Comment by slindberg** [comment]
@Truffula is this still an issue for you? If not would you mind closing?

**Comment by Truffula** [comment]
All good, thanks for your time!
