### ISSUE TITLE
`MF.array('string')` gets clobbered when saving and updating

### ISSUE THREAD

**Issue by workmanw** [lytics/ember-data-model-fragments#176]
We discovered an issue in our app that revolves around pushing model updates when a string fragment array attribute (`MF.array('string')`) has a dirty value.

The best was for me to explain it is via this JSBin: http://emberjs.jsbin.com/gixizajoka/1/edit?html,js,output That JSBin has four buttons that represent the sequence of events necessary to reproduce the issue. If you click each of the four buttons, one by one, you'll reproduce the issue. Let me break it down by steps what's happening. 

1) The model is updated, resulting in two dirty attributes (a string and a fragment string array). Save begins, changing the model to an `inFlight` state.
2) While `inFlight` those two properties are updated again.
3) Save completes with a fresh copy of the data from the server (for save 1).

** You'll notice that the string property keeps it's second updated value. Meaning the server returns the first updated value and this change is merged. However, the fragment array value is not merged, it is clobbered.

========

Our user scenario for this is a "tag control" that allows users to rapidly add tags and is periodically saving in the background (debounce). Here is a gif:

![tags](https://cloud.githubusercontent.com/assets/825487/12485711/91ee7666-c02d-11e5-8afc-a9944b97213f.gif)

========

I believe this issue also exists in other forms as well, for example, if a fragment array is updated (dirty) and a realtime update comes through and does `store.push`.

**Comment by slindberg** [comment]
You really push this addon to the limit :smile:

I'm not surprised this is an issue, since there's currently no concept of 'in-flight' for fragment arrays (or fragments for that matter). I am surprised however that nobody has reported this until now.

Sooo, this isn't a trivial fix. First, it will require adding `inFlight` states to the state machine and creating some kind of `_inFlightFragments` property that is a snapshot of the array. Then, in the `adapterDidCommit` path, the current array will need to be diffed with the in-flight snapshot to generate some kind of change set, which then is applied to the array in the response (because the response can differ from what was in the payload). The hard part is nailing down the merge semantics, i.e. what happens when adjacent element paris are swapped in both the current array and the array response? Simple adds/removes are straightforward, but it get's complicated quick. Merge conflicts yo. I seem to recall an emberconf talk on how rich webapps are essentially distributed databases...

:neutral_face:

**Comment by workmanw** [comment]
> You really push this addon to the limit :smile:

Haha. Yea, I told our PM that when he reported this issue to me :P

> I'm not surprised this is an issue, since there's currently no concept of 'in-flight' for fragment arrays (or fragments for that matter). I am surprised however that nobody has reported this until now.

> Sooo, this isn't a trivial fix. First, it will require adding inFlight states to the state machine and creating some kind of _inFlightFragments property that is a snapshot of the array. Then, in the adapterDidCommit path, the current array will need to be diffed with the in-flight snapshot to generate some kind of change set, which then is applied to the array in the response (because the response can differ from what was in the payload). The hard part is nailing down the merge semantics, i.e. what happens when adjacent element paris are swapped in both the current array and the array response? Simple adds/removes are straightforward, but it get's complicated quick. Merge conflicts yo. I seem to recall an emberconf talk on how rich webapps are essentially distributed databases...


Alright. Let's leave the ball in my court here. I'll see if I can come up with something, if not I may just close it and work around it in my app by locking the UI or something. Thank you!

**Comment by workmanw** [comment]
@slindberg So I've spent the last 4 days straight learning the architecture of this addon, specifically with the goal of making this `_inFlight` state idea work. This would be an accurate describe my view of this issue:

![mindblown](https://cloud.githubusercontent.com/assets/825487/12997310/085b3a94-d106-11e5-90fe-128f0af6db35.gif)


In all seriousness, I completely appreciate what you're saying now. This being "non-trivial" is putting it lightly. While I would still support a solution to this problem, I honestly believe it's outside the scope of our capabilities at this point.

**Comment by slindberg** [comment]
Thanks for taking the time to look into it. The in-flight states would be a pain for sure, but for the most part would mirror DS.Model's states. The real problem is the merge semantics, which is basically the reason that MF is an addon and not part of ED itself.

This got me thinking: is this something that relations suffer from as well? Relations don't have an in-flight state, so what happens if you add to a hasMany relationship while a record is saving, does the response clobber it? Relationships being a set makes it a less difficult problem, but it still seems like it would be an issue.
