### ISSUE TITLE
Deprecation warning "Calling Ember.get without a target object" on 1.13.3

### ISSUE THREAD

**Issue by FredUK** [lytics/ember-data-model-fragments#191]
Hi, first of all thanks a lot for this great addon.

I've been for the past few days trying to update my Ember app to 1.13.13 with Ember data 1.13.15 with your latest Data Model Fragments 1,13,3 before I even try update to v2 and noticed a deprecation warning I can't seem to fix and according to the call stack the last call before the warning, comes from [fragment.js#L129](https://github.com/lytics/ember-data-model-fragments/blob/f7ac7fce03701587e56473cca63a85b8ca640267/addon/fragment.js#L129)

![image](https://cloud.githubusercontent.com/assets/11350311/14212671/e12f5db8-f82b-11e5-8056-88bed1857481.png)

Can you confirm and perhaps shed any light why this is/might be happening?

Thanks a lot.
Cheers, Fred

**Comment by slindberg** [comment]
It looks like what's happening is `toString` is getting called on a fragment that hasn't been added to a record yet (i.e. created with `store.createFragment`, but never added to a record with `record.set('prop', fragment')`). Usually this happens when debugging, since records/fragments rarely get coerced into strings under normal circumstances; are you `console.log`ing the record in that call stack?

We definitely should be checking whether the fragment has an owner record before calling `Ember.get` on it, so this is a bug. In v2 calling `Ember.get(null)` throws an exception, so this code path will definitely break your app. I would suggest avoiding calling `toString` on fragments until it's fixed. Thanks for reporting.

**Comment by slindberg** [comment]
Fixed by #194 and included in v2.3.1
