### ISSUE TITLE
FragmentTransform does not have store during test

### ISSUE THREAD

**Issue by ming-codes** [lytics/ember-data-model-fragments#263]
I'm on `ember-data-model-fragments@2.11.2`.

During serializer unit tests, `FragmentTransform#deserializeSingle` does not have the store injected.

Instead of `store: null`, we should just inject the store service in here right?

**Comment by workmanw** [comment]
I think this might be similar to https://github.com/lytics/ember-data-model-fragments/issues/211 because it's a unit test. I suspect the problem is that the initializers didn't run to setup the owner injections.

**Comment by ming-codes** [comment]
I don't understand. I looked at the `ember-data-model-fragments` initializer. It's only used to register transforms. How is this related to the `store` not present on the transform? There are no documentation from `ember-data` that says `store` is automatically injected on all transforms either.

There's a RFC to [deprecate `ember-data` initializers](https://github.com/emberjs/rfcs/blob/8f302c78b1f9fc6463ebecb202abac1fea21e207/text/0181-deprecate-ember-data-initializers.md). So it's even less likely that `store` will be injected into transforms.

**Comment by workmanw** [comment]
> There are no documentation from ember-data that says store is automatically injected on all transforms either.

I swear this use to be the case. I would have bet money that Ember-data was injecting the store onto transforms at one point in it's history. But I went back to ember-data-1.x and could find not evidence of that. That was definitely my mistake. Apologies.

> There's a RFC to deprecate ember-data initializers. So it's even less likely that store will be injected into transforms.

I could be mistaken, but I believe that RFC is just about consolidating the various initializers that have been added in recent versions into simply an `ember-data` initializer. At least that was my understanding after #226. 

-----------

So doing some more digging and thinking, I'm not sure what the right path forward is. In a booted application this works normally because `getFragmentTransform` does the setup work ([addon/ext.js](https://github.com/lytics/ember-data-model-fragments/blob/master/addon/ext.js#L304-L329)). Obviously that is not the case for a unit test. In fact, I'm not sure that a store would event exist during a unit test. So even using the `owner.inject` or `Ember.inject.service` I don't think would work right in a unit test.

So I looked at ember-data-model-fragment tests and they're all working because they're acceptance tests which boot the app like normal, fire initializers, etc. 

To me it seems like this may simply not be unit testable, rather only integration or acceptance testable. I'm definitely open to suggestions here. CC: @jakesjews
